export const actionTypes = {
  //  auth
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAIL: 'LOGIN_FAIL',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGIN_ERROR_MES_OVERALL: 'LOGIN_ERROR_MES_OVERALL',

  // works
  REQUEST_WORKS: 'REQUEST_WORKS',
  LOAD_WORKS_OK: 'LOAD_WORKS_OK',
  LOAD_WORKS_FAIL: 'LOAD_WORKS_FAIL',

  REQUEST_ADD_WORK: 'REQUEST_ADD_WORK',
  ADD_WORK_OK: 'ADD_WORK_OK',
  ADD_WORK_FAIL: 'ADD_WORK_FAIL',

  REQUEST_WORK_ITEM: 'REQUEST_WORK_ITEM',
  WORK_ITEM_OK: 'WORK_ITEM_OK',
  WORK_ITEM_FAIL: 'WORK_ITEM_FAIL',

  REQUEST_UPDATE_WORK: 'REQUEST_UPDATE_WORK',
  UPDATE_WORK_OK: 'UPDATE_WORK_OK',
  UPDATE_WORK_FAIL: 'UPDATE_WORK_FAIL',

  REQUEST_WORK_DELETE: 'REQUEST_WORK_DELETE',
  WORK_DELETE_OK: 'WORK_DELETE_OK',
  WORK_DELETE_FAIL: 'WORK_DELETE_FAIL',

  REQUEST_ADD_IMAGES_WORK: 'REQUEST_ADD_IMAGES_WORK',
  ADD_IMAGES_WORK_OK: 'ADD_IMAGES_WORK_OK',
  ADD_IMAGES_WORK_FAIL: 'ADD_IMAGES_WORK_FAIL',

  // images
  REQUEST_IMAGES: 'REQUEST_IMAGES',
  LOAD_IMAGES_OK: 'LOAD_IMAGES_OK',
  LOAD_IMAGES_FAIL: 'LOAD_IMAGES_FAIL',

  REQUEST_ADD_IMAGE: 'REQUEST_ADD_IMAGE',
  ADD_IMAGE_OK: 'ADD_IMAGE_OK',
  ADD_IMAGE_FAIL: 'ADD_IMAGE_FAIL',

  REQUEST_IMAGE_DELETE: 'REQUEST_IMAGE_DELETE',
  IMAGE_DELETE_OK: 'IMAGE_DELETE_OK',
  IMAGE_DELETE_FAIL: 'IMAGE_DELETE_FAIL',

  // clients
  REQUEST_CLIENTS: 'REQUEST_CLIENTS',
  LOAD_CLIENTS_OK: 'LOAD_CLIENTS_OK',
  LOAD_CLIENTS_FAIL: 'LOAD_CLIENTS_FAIL',

  REQUEST_ADD_CLIENT: 'REQUEST_ADD_CLIENT',
  ADD_CLIENT_OK: 'ADD_CLIENT_OK',
  ADD_CLIENT_FAIL: 'ADD_CLIENT_FAIL',

  REQUEST_CLIENT_DELETE: 'REQUEST_CLIENT_DELETE',
  CLIENT_DELETE_OK: 'CLIENT_DELETE_OK',
  CLIENT_DELETE_FAIL: 'CLIENT_DELETE_FAIL',

  REQUEST_CLIENT_UPDATE: 'REQUEST_CLIENT_UPDATE',
  CLIENT_UPDATE_OK: 'CLIENT_UPDATE_OK',
  CLIENT_UPDATE_FAIL: 'CLIENT_UPDATE_FAIL',

  REQUEST_CLIENT_ITEM: 'REQUEST_CLIENT_ITEM',
  CLIENT_ITEM_OK: 'CLIENT_ITEM_OK',
  CLIENT_ITEM_FAIL: 'CLIENT_ITEM_FAIL',

  // technologies
  REQUEST_TECHNOLOGIES: 'REQUEST_TECHNOLOGIES',
  LOAD_TECHNOLOGIES_OK: 'LOAD_TECHNOLOGIES_OK',
  LOAD_TECHNOLOGIES_FAIL: 'LOAD_TECHNOLOGIES_FAIL',

  REQUEST_ADD_TECHNOLOGIES: 'REQUEST_ADD_TECHNOLOGIES',
  ADD_TECHNOLOGIES_OK: 'ADD_TECHNOLOGIES_OK',
  ADD_TECHNOLOGIES_FAIL: 'ADD_TECHNOLOGIES_FAIL',

  REQUEST_TECHNOLOGY_DELETE: 'REQUEST_TECHNOLOGY_DELETE',
  TECHNOLOGY_DELETE_OK: 'TECHNOLOGY_DELETE_OK',
  TECHNOLOGY_DELETE_FAIL: 'TECHNOLOGY_DELETE_FAIL',

  REQUEST_TECHNOLOGY_ITEM: 'REQUEST_TECHNOLOGY_ITEM',
  TECHNOLOGY_ITEM_OK: 'TECHNOLOGY_ITEM_OK',
  TECHNOLOGY_ITEM_FAIL: 'TECHNOLOGY_ITEM_FAIL',

  REQUEST_TECHNOLOGY_UPDATE: 'REQUEST_TECHNOLOGY_UPDATE',
  TECHNOLOGY_UPDATE_OK: 'TECHNOLOGY_UPDATE_OK',
  TECHNOLOGY_UPDATE_FAIL: 'TECHNOLOGY_UPDATE_FAIL',

  REQUEST_CATEGORIES: 'REQUEST_CATEGORIES',
  LOAD_CATEGORIES_OK: 'LOAD_CATEGORIES_OK',
  LOAD_CATEGORIES_FAIL: 'LOAD_CATEGORIES_FAIL',

  REQUEST_CATEGORY_ITEM: 'REQUEST_CATEGORY_ITEM',
  CATEGORY_ITEM_OK: 'CATEGORY_ITEM_OK',
  CATEGORY_ITEM_FAIL: 'CATEGORY_ITEM_FAIL',

  REQUEST_ADD_CATEGORIES: 'REQUEST_ADD_CATEGORIES',
  ADD_CATEGORIES_OK: 'ADD_CATEGORIES_OK',
  ADD_CATEGORIES_FAIL: 'ADD_CATEGORIES_FAIL',

  REQUEST_CATEGORY_DELETE: 'REQUEST_CATEGORY_DELETE',
  CATEGORY_DELETE_OK: 'CATEGORY_DELETE_OK',
  CATEGORY_DELETE_FAIL: 'CATEGORY_DELETE_FAIL',

  REQUEST_CATEGORY_UPDATE: 'REQUEST_CATEGORY_UPDATE',
  CATEGORY_UPDATE_OK: 'CATEGORY_UPDATE_OK',
  CATEGORY_UPDATE_FAIL: 'CATEGORY_UPDATE_FAIL',

  //  overall
  CHANGE_TOKEN: 'CHANGE_TOKEN',
  GET_ROLES: 'GET_ROLES',
  LOADED_APP_INACTIVE: 'LOADED_APP_INACTIVE',
  NETWORK_ACTIVE: 'NETWORK_ACTIVE',
  NETWORK_INACTIVE: 'NETWORK_INACTIVE',
  SET_ORG: 'SET_ORG',
  HEADER_CHANGE_TITLE: 'HEADER_CHANGE_TITLE',
  HEADER_CHANGE_NAVIGATION_BAR: 'HEADER_CHANGE_NAVIGATION_BAR',
  MQL: 'MQL',
  TOGGLE_SIDEBAR: 'TOGGLE_SIDEBAR',
  TOGGLE_MOBILE_SIDEBAR: 'TOGGLE_MOBILE_SIDEBAR',

  ABOUT_DIALOG_PREVIEW: 'ABOUT_DIALOG_PREVIEW',
  ALERT_DIALOG_PREVIEW: 'ALERT_DIALOG_PREVIEW',
  OVERVIEW_PAGE_SUCCESS: 'OVERVIEW_PAGE_SUCCESS',
  OVERVIEW_PAGE_CONTACTS_SUCCESS: 'OVERVIEW_PAGE_CONTACTS_SUCCESS',

  //  admin page
  ADMIN_PAGE_TABLE_SUCCESS: 'ADMIN_PAGE_TABLE_SUCCESS',
  ADMIN_PAGE_DIALOG_ADD: 'ADMIN_PAGE_DIALOG_ADD',
  ADMIN_PAGE_DIALOG_EDIT: 'ADMIN_PAGE_DIALOG_EDIT'
}
